# Site settings
title: Храм "Света Троица", гр. София, район "Слатина"
description: Официална информационна страница на православен храм "Света Троица", гр. София, район "Слатина"
baseurl: "" # the subpath of your site, e.g. /blog
url: "sveta-troitsa.eu" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Храм "Света Троица"
    hero_description: Официална информационна страница на православен храм "Света Троица"и старинен слатински храм "Свети Великомъченик Мина"

# Contact form
api_token: 53d1e2fe18ac2125705223776dc615d8 # Enter API token here

# Contact info
contact:
    phone: 02 872 0970
    emergency: 02 872 0970
    email: contact@sveta-troitsa.eu
    address: ул. "Манастирска" 45, <br>ж.к. "Гео Милев", район "Слатина",<br>гр. София, 1111

# Opening hours
monday_friday: 7:00 – 19:00
saturday: 7:30 – 18:00
sunday: 

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Manastirska St 45, 1111 ж.к. Гео Милев, Sofia
    address_details: /svg/logo.svg

# Social settings
facebook: http://www.facebook.com/291873434171269/
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: ""
feed: yes

# Footer
copyright: © 2017 Храм "Света Троица" 
terms: <a href="terms.html" target="_parent" name="Условия за ползване" title="Условия за ползване"> Условия за ползване</a>


# Build settings
markdown: kramdown

exclude: [
    package.json,
    package-lock.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    LICENSE.md,
    README.md
]

# Theme Settings
analytics: UA-6871537-12
google_verification:
